version: '3'
services: 
    frontend:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes: 
            - /usr/react-app-frontend/node_modules
            - .:/usr/react-app-frontend
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /usr/react-app-frontend/node_modules
            - .:/usr/react-app-frontend
        command: ["npm","run","test"]

